const stations = [
  {
    id: "north-haw-creek",
    name: "North Haw Creek",
    area: "Haw Creek",
    latitude: 35.61564246229161,
    longitude: -82.50557699955283,
    elevationFt: 2331,
    exposure: "Residential with trees",
    publicCoordinatePrecision: 3,
    source: { provider: "tempest", stationId: "127602" },
    aliases: ["tempest:127602"]
  },
  {
    id: "biltmore-forest",
    name: "Biltmore Forest",
    area: "Biltmore Forest",
    latitude: 35.53524238568249,
    longitude: -82.54195798036217,
    elevationFt: 2167,
    exposure: "Residential with heavy forest cover and grass",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCBILTM2" },
    aliases: ["wunderground:KNCBILTM2"]
  },
  {
    id: "five-points-neighborhood",
    name: "Five Points Neighborhood",
    area: "North Asheville",
    latitude: 35.60683469484683,
    longitude: -82.55700694359045,
    elevationFt: 2147,
    exposure: "Residential with trees and shrubbery",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV275" },
    aliases: ["wunderground:KNCASHEV275"]
  },
  {
    id: "grove-arcade",
    name: "Grove Arcade",
    area: "Downtown Asheville",
    latitude: 35.59528790285582,
    longitude: -82.55671331039254,
    elevationFt: 2240,
    exposure: "Rooftop with little obstruction",
    publicCoordinatePrecision: 5,
    source: {
      provider: "ncei",
      stationId: "grove-arcade",
      endpoint: "https://www.ncei.noaa.gov/access/asheville-weather/station-data/current.json"
    },
    aliases: ["wunderground:KNCASHEV475", "pwsweather:C9566", "cwop:CW9566"]
  },
  {
    id: "river-arts-district",
    name: "River Arts District",
    area: "River Arts District",
    latitude: 35.58588960462158,
    longitude: -82.57494368590235,
    elevationFt: 2100,
    exposure: "Residential with trees and shrubs",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV276" },
    aliases: ["wunderground:KNCASHEV276"]
  },
  {
    id: "west-asheville",
    name: "West Asheville",
    area: "West Asheville",
    latitude: 35.584047108056645,
    longitude: -82.59807435919438,
    elevationFt: 2174,
    exposure: "Residential",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV461" },
    aliases: ["wunderground:KNCASHEV461"]
  },
  {
    id: "biltmore-lake",
    name: "Biltmore Lake",
    area: "Biltmore Lake",
    latitude: 35.532516769947875,
    longitude: -82.65231652212547,
    elevationFt: 2107,
    exposure: "Residential, lakeside, and forested",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCBILTM9" },
    aliases: ["wunderground:KNCBILTM9"]
  },
  {
    id: "biltmore-park",
    name: "Biltmore Park",
    area: "South Asheville",
    latitude: 35.48901,
    longitude: -82.55599,
    elevationFt: 2200,
    exposure: "Residential with grass",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV400" },
    aliases: ["wunderground:KNCASHEV400"]
  },
  {
    id: "east-asheville",
    name: "Asheville Municipal Golf Course",
    area: "East Asheville",
    latitude: 35.58113,
    longitude: -82.50498,
    elevationFt: 2106,
    exposure: "Residential with grass",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV167" },
    aliases: ["wunderground:KNCASHEV167"]
  },
  {
    id: "ac-reynolds-middle-school",
    name: "Near AC Reynolds Middle School",
    area: "East Asheville",
    latitude: 35.5549475023305,
    longitude: -82.49185386894641,
    elevationFt: 2245,
    exposure: "Heavily forested",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV419" },
    aliases: ["wunderground:KNCASHEV419"]
  },
  {
    id: "bent-creek",
    name: "Bent Creek",
    area: "Bent Creek",
    latitude: 35.51094,
    longitude: -82.6098,
    elevationFt: 2200,
    exposure: "Residential with grass and trees",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV389" },
    aliases: ["wunderground:KNCASHEV389"]
  },
  {
    id: "grove-park",
    name: "Grove Park",
    area: "North Asheville",
    latitude: 35.62653,
    longitude: -82.54562,
    elevationFt: 2266,
    exposure: "Residential with partial open exposure",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV37" },
    aliases: ["wunderground:KNCASHEV37"]
  },
  {
    id: "beaverdam-country-club",
    name: "Beaverdam / Country Club",
    area: "North Asheville",
    latitude: 35.6409831731172,
    longitude: -82.54702008463879,
    elevationFt: 2165,
    exposure: "Residential with minimal obstruction",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCASHEV431" },
    aliases: ["wunderground:KNCASHEV431"]
  },
  {
    id: "woodfin",
    name: "Woodfin",
    area: "Greater Asheville — north",
    latitude: 35.63,
    longitude: -82.58,
    elevationFt: 2089,
    exposure: "Residential with grass and trees",
    publicCoordinatePrecision: 2,
    scope: "metro",
    source: { provider: "wunderground", stationId: "KNCWOODF17" },
    aliases: ["wunderground:KNCWOODF17"]
  },
  {
    id: "swannanoa",
    name: "Swannanoa",
    area: "Greater Asheville — east",
    latitude: 35.6,
    longitude: -82.4,
    elevationFt: 2182,
    exposure: "Residential and fairly unobstructed",
    publicCoordinatePrecision: 2,
    scope: "metro",
    source: { provider: "wunderground", stationId: "KNCSWANN72" },
    aliases: ["wunderground:KNCSWANN72"]
  },
  {
    id: "arden",
    name: "Arden",
    area: "Greater Asheville — south",
    latitude: 35.47418209045869,
    longitude: -82.51427510361128,
    elevationFt: 2295,
    exposure: "Residential with trees and shrubbery",
    publicCoordinatePrecision: 3,
    scope: "metro",
    source: { provider: "wunderground", stationId: "KNCARDEN41" },
    aliases: ["wunderground:KNCARDEN41"]
  },
  {
    id: "candler",
    name: "Candler",
    area: "Greater Asheville — west",
    latitude: 35.55328783875344,
    longitude: -82.70654456656287,
    elevationFt: 2189,
    exposure: "Rural residential and mostly unobstructed",
    publicCoordinatePrecision: 3,
    scope: "metro",
    source: { provider: "wunderground", stationId: "KNCCANDL27" },
    aliases: ["wunderground:KNCCANDL27"]
  },
  {
    id: "weaverville",
    name: "Weaverville",
    area: "North mountain corridor",
    latitude: 35.69194778711192,
    longitude: -82.56597332817688,
    elevationFt: 2107,
    exposure: "Residential with some trees",
    publicCoordinatePrecision: 3,
    scope: "corridor",
    corridor: "north",
    source: { provider: "wunderground", stationId: "KNCWEAVE201" },
    aliases: ["wunderground:KNCWEAVE201"]
  },
  {
    id: "mars-hill",
    name: "Mars Hill",
    area: "North mountain corridor",
    latitude: 35.83030755250296,
    longitude: -82.52109613984135,
    elevationFt: 2329,
    exposure: "Rural agricultural setting and mostly unobstructed",
    publicCoordinatePrecision: 3,
    scope: "corridor",
    corridor: "north",
    source: { provider: "wunderground", stationId: "KNCMARSH66" },
    aliases: ["wunderground:KNCMARSH66"]
  },
  {
    id: "black-mountain",
    name: "Black Mountain",
    area: "East mountain corridor",
    latitude: 35.620113558341885,
    longitude: -82.29639209462947,
    elevationFt: 2574,
    exposure: "Residential and heavily forested",
    publicCoordinatePrecision: 3,
    scope: "corridor",
    corridor: "east",
    source: { provider: "wunderground", stationId: "KNCBLACK203" },
    aliases: ["wunderground:KNCBLACK203"]
  },
  {
    id: "old-fort",
    name: "Old Fort",
    area: "East mountain corridor",
    latitude: 35.62970442231749,
    longitude: -82.18012862451593,
    elevationFt: 1444,
    exposure: "Main Street firehouse rooftop and unobstructed",
    publicCoordinatePrecision: 3,
    scope: "corridor",
    corridor: "east",
    source: { provider: "wunderground", stationId: "KNCOLDFO12" },
    aliases: ["wunderground:KNCOLDFO12"]
  },
  {
    id: "fletcher",
    name: "Fletcher",
    area: "South mountain corridor",
    latitude: 35.42383863146818,
    longitude: -82.50948863258745,
    elevationFt: 2067,
    exposure: "Residential with trees and shrubbery",
    publicCoordinatePrecision: 3,
    scope: "corridor",
    corridor: "south",
    source: { provider: "wunderground", stationId: "KNCFLETC53" },
    aliases: ["wunderground:KNCFLETC53"]
  },
  {
    id: "hendersonville",
    name: "Hendersonville",
    area: "South mountain corridor",
    latitude: 35.32115321197063,
    longitude: -82.48058956229477,
    elevationFt: 2200,
    exposure: "Residential with trees and shrubbery",
    publicCoordinatePrecision: 3,
    scope: "corridor",
    corridor: "south",
    source: { provider: "wunderground", stationId: "KNCHENDE608" },
    aliases: ["wunderground:KNCHENDE608"]
  },
  {
    id: "canton",
    name: "Canton",
    area: "West mountain corridor",
    latitude: 35.52951339886919,
    longitude: -82.84226106246729,
    elevationFt: 2585,
    exposure: "Residential rooftop and mostly unobstructed",
    publicCoordinatePrecision: 3,
    scope: "corridor",
    corridor: "west",
    source: { provider: "wunderground", stationId: "KNCCANTO154" },
    aliases: ["wunderground:KNCCANTO154"]
  },
  {
    id: "waynesville",
    name: "Waynesville",
    area: "West mountain corridor",
    latitude: 35.4820998165842,
    longitude: -82.99901511070124,
    elevationFt: 2800,
    exposure: "Residential with trees and shrubbery",
    publicCoordinatePrecision: 3,
    scope: "corridor",
    corridor: "west",
    source: { provider: "wunderground", stationId: "KNCWAYNE342" },
    aliases: ["wunderground:KNCWAYNE342"]
  },
  {
    id: "sand-hill",
    name: "Sand Hill",
    area: "Sand Hill community",
    latitude: 35.56388278903192,
    longitude: -82.65427528077103,
    elevationFt: 2232,
    exposure: "Residential with trees",
    publicCoordinatePrecision: 3,
    source: { provider: "wunderground", stationId: "KNCCANDL104" },
    aliases: ["wunderground:KNCCANDL104"]
  },
  {
    id: "biltmore-village",
    name: "Biltmore Village",
    area: "Biltmore Village",
    latitude: 35.5651,
    longitude: -82.54016,
    elevationFt: 2048,
    exposure: "Residential",
    publicCoordinatePrecision: 3,
    source: { provider: "tempest", stationId: "131000" },
    aliases: ["tempest:131000"]
  },
  {
    id: "asheville-high-school",
    name: "Asheville High School",
    area: "Victoria Road",
    latitude: 35.57437070691971,
    longitude: -82.55791310078509,
    elevationFt: 2129,
    exposure: "Residential setting",
    publicCoordinatePrecision: 3,
    enabled: false,
    unavailableReason: "Authorized machine-readable feed not configured",
    source: { provider: "pwsweather", stationId: "VICTORIA" },
    aliases: ["pwsweather:VICTORIA"]
  },
  {
    id: "unc-asheville",
    name: "UNC Asheville",
    area: "Lookout Observatory",
    latitude: 35.621802282303385,
    longitude: -82.56608557099108,
    elevationFt: 2357,
    exposure: "Fully unobstructed research tower",
    publicCoordinatePrecision: 5,
    source: { provider: "econet", stationId: "UNCA" },
    aliases: ["econet:UNCA"]
  },
  {
    id: "biltmore-estate",
    name: "Biltmore Estate",
    area: "Biltmore Estate",
    latitude: 35.55662920742926,
    longitude: -82.58046541650717,
    elevationFt: 2185,
    exposure: "Open agricultural field",
    publicCoordinatePrecision: 5,
    enabled: false,
    unavailableReason: "WeatherLink access is not authorized",
    source: { provider: "weatherlink", stationId: "4bd35a49-54f2-4a48-bb7c-58c370cdc992" },
    aliases: ["weatherlink:4bd35a49-54f2-4a48-bb7c-58c370cdc992"]
  }
];

export const ASHEVILLE_STATIONS = Object.freeze(stations.map((station) => Object.freeze(station)));

export function publicStationMetadata(station) {
  const precision = station.publicCoordinatePrecision ?? 3;
  return {
    id: station.id,
    name: station.name,
    area: station.area,
    location: {
      latitude: Number(station.latitude.toFixed(precision)),
      longitude: Number(station.longitude.toFixed(precision)),
      precision: precision >= 5 ? "site" : "neighborhood"
    },
    elevationFt: station.elevationFt,
    exposure: station.exposure,
    provider: station.source.provider,
    providerStationId: station.source.stationId,
    aliases: [...station.aliases],
    scope: station.scope ?? "core",
    corridor: station.corridor ?? null,
    enabled: station.enabled !== false
  };
}
