import test from "node:test";
import assert from "node:assert/strict";
import {getConfig,windowStatus,manualOverrideActive} from "../lib/forecast/config.js";
import {validateForecast} from "../lib/forecast/validate.js";
import {runAutomaticForecast} from "../lib/forecast/service.js";

const enabled={AUTO_FORECAST_ENABLED:"true"};
test("before vacation window is blocked",()=>assert.equal(windowStatus(getConfig(enabled),new Date("2026-07-12T23:59:59-04:00")).inside,false));
test("start of vacation window is allowed",()=>assert.equal(windowStatus(getConfig(enabled),new Date("2026-07-13T00:00:00-04:00")).inside,true));
test("during vacation window is allowed",()=>assert.equal(windowStatus(getConfig(enabled),new Date("2026-07-20T12:00:00-04:00")).inside,true));
test("final July 26 morning update is allowed",()=>assert.equal(windowStatus(getConfig(enabled),new Date("2026-07-26T05:15:00-04:00")).inside,true));
test("after vacation endpoint is blocked",()=>assert.equal(windowStatus(getConfig(enabled),new Date("2026-07-26T08:00:01-04:00")).inside,false));
test("disabled flag wins",()=>assert.equal(windowStatus(getConfig({AUTO_FORECAST_ENABLED:"false"}),new Date("2026-07-20T12:00:00-04:00")).inside,false));
test("force cannot bypass the vacation window",async()=>{const result=await runAutomaticForecast({force:true,now:new Date("2026-07-27T09:15:00Z"),env:enabled,dependencies:{saveStatus:async()=>{}}});assert.equal(result.status,"skipped");assert.equal(result.reason,"outside vacation window");});
test("EDT timestamps retain intended UTC conversion",()=>{assert.equal(new Date(getConfig(enabled).start).toISOString(),"2026-07-13T04:00:00.000Z");assert.equal(new Date(getConfig(enabled).end).toISOString(),"2026-07-26T12:00:00.000Z");});
test("recent manual publication is protected",()=>assert.equal(manualOverrideActive({source:"manual-composer",lastUpdated:"2026-07-20T10:00:00Z"},getConfig(enabled),new Date("2026-07-20T14:00:00Z")),true));
test("expired manual publication is unprotected",()=>assert.equal(manualOverrideActive({source:"manual-composer",lastUpdated:"2026-07-20T05:00:00Z"},getConfig(enabled),new Date("2026-07-20T14:00:00Z")),false));

test("dry run never publishes",async()=>{let published=false;const result=await runAutomaticForecast({dryRun:true,now:new Date("2026-07-20T09:15:00Z"),env:enabled,dependencies:{loadForecast:async()=>({}),fetchSources:async()=>sources(),generateForecast:()=>candidate(),validateForecast:()=>({valid:true,errors:[],warnings:[],validDays:4}),publishForecast:async()=>{published=true;}}});assert.equal(result.status,"preview");assert.equal(published,false);});
test("recent manual forecast returns a successful skip",async()=>{const result=await runAutomaticForecast({now:new Date("2026-07-20T14:00:00Z"),env:enabled,dependencies:{loadForecast:async()=>({source:"manual-composer",lastUpdated:"2026-07-20T10:00:00Z"})}});assert.equal(result.status,"skipped");assert.equal(result.manualOverride,true);});
test("validation failure preserves last known good",async()=>{let published=false;const result=await runAutomaticForecast({now:new Date("2026-07-20T09:15:00Z"),env:enabled,dependencies:{loadForecast:async()=>({source:"automatic"}),acquireLock:async()=>true,releaseLock:async()=>{},fetchSources:async()=>sources(),generateForecast:()=>candidate(),validateForecast:()=>({valid:false,errors:["bad"]}),publishForecast:async()=>{published=true;}}});assert.equal(result.status,"failed");assert.equal(published,false);});
test("duplicate invocation is skipped",async()=>{const result=await runAutomaticForecast({now:new Date("2026-07-20T09:15:00Z"),env:enabled,dependencies:{loadForecast:async()=>({source:"automatic"}),acquireLock:async()=>false}});assert.equal(result.reason,"duplicate run already in progress");});
test("NWS failure is contained",async()=>{const result=await runAutomaticForecast({now:new Date("2026-07-20T09:15:00Z"),env:enabled,dependencies:{loadForecast:async()=>({}),acquireLock:async()=>true,releaseLock:async()=>{},fetchSources:async()=>{throw new Error("NWS request failed");}}});assert.equal(result.status,"failed");assert.match(result.reason,/NWS/);});
test("banned phrases fail style validation",()=>{const value=candidate();value.days[Object.keys(value.days)[0]].narrative="Residents should remain weather aware.";assert.equal(validateForecast(value).valid,false);});
test("unsupported severe wording is rejected",()=>{const value=candidate();value.days[Object.keys(value.days)[0]].narrative="Severe storms are expected.";assert.equal(validateForecast(value).valid,false);});
test("substantially repeated narratives are rejected",()=>assert.equal(validateForecast(candidate()).valid,false));
test("four ordered and editorially distinct days pass validation",()=>{const value=candidate();const narratives=["Sun gives way to building clouds and a late shower.","The morning stays dry before spotty rain develops later.","Clouds linger early, then brighter breaks arrive by midday.","A quieter setup brings sunshine and comfortable afternoon weather."];Object.values(value.days).forEach((day,index)=>day.narrative=narratives[index]);assert.equal(validateForecast(value).valid,true);});
test("manual composer validation allows optional null editorial fields",()=>{const value=candidate();Object.values(value.days).forEach(day=>{day.narrative=null;day.condition=null;day.mainIssue=null;day.bestWindow=null;day.high=null;day.low=null;day.wind={direction:null,speedMin:null,speedMax:null,calm:false,gust:null,gustNA:false};});assert.equal(validateForecast(value,{mode:"manual"}).valid,true);assert.equal(validateForecast(value).valid,false);});

function sources(){return {timestamps:{forecastUpdated:"2026-07-20T08:00:00Z",afdIssued:"2026-07-20T08:00:00Z"},afd:{}};}
function candidate(){const days={};for(let i=0;i<4;i++){const date=`2026-07-${String(21+i).padStart(2,"0")}`;days[date]={date,headline:`Useful Weather Window ${i+1}`,narrative:"Clouds build during the afternoon, with a brief shower possible later.",condition:"Partly cloudy",high:82+i,low:64,feelScore:75,mainIssue:"Spotty rain",bestWindow:"Morning",wind:{direction:"SW",speedMin:4,speedMax:9,calm:false,gust:null,gustNA:true},sky:"partly_cloudy",evolution:"building",humidity:"moderate",stormRisk:"possible",rainWindow:{start:"4 PM",end:"7 PM"},timeline:{morning:"Dry with some early sun",midday:"Warm and mainly dry",afternoon:"A few showers possible",evening:"A shower fades"},localNote:"Ridges may stay cloudier longer.",tags:["rain chance"],confidence:.75,needsReview:false};}return {boardHeadline:"Daily Timing Matters",boardSummary:"A few showers are possible across the stretch.",rainRisk:"medium",comfortTrend:"steady",bestOutdoorDay:"Tuesday",forecastConfidence:75,weekAheadSignals:{global:{weatherPattern:"Summer"},cards:[]},days,global:{tone:"human",style:"concise",overrideNarrative:true}};}
